services:
  - type: web
    name: lps-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATABASE_URL
        fromDatabase:
          name: lps-db
          property: connectionString

databases:
  - name: lps-db
    databaseName: lps_production
    user: lps_user
